# vim:set ts=8 sts=2 sw=2 tw=0 et ft=sh:

user="unsloth"
model="gemma-4-26B-A4B-it-qat-GGUF"
quant="UD-Q4_K_XL"

args=(
  # See: https://unsloth.ai/docs/models/gemma-4
  --temp 1.0 
  --top-p 0.95 
  --top-k 64 
  --reasoning on

  --n-cpu-moe 16

  -fa on
)
