# vim:set ts=8 sts=2 sw=2 tw=0 et ft=sh:

user="unsloth"
model="gemma-4-12B-it-qat-GGUF"
quant="UD-Q4_K_XL"

args=(
  # See: https://unsloth.ai/docs/models/gemma-4/qat
  --temp 1.0
  --top-p 0.95
  --top-k 64

  # Reasoning
  --reasoning on

  # Layer layout
  --fit off

  # Prefill
  --flash-attn on
  -ctk q8_0 -ctv q8_0

  # Decoder
  --spec-type draft-mtp
  --spec-draft-n-max 4
)
