# vim:set ts=8 sts=2 sw=2 tw=0 et ft=sh:

user="unsloth"
model="gpt-oss-20b-GGUF"
quant="Q4_K_M"

args=(
  # See: https://unsloth.ai/docs/models/gpt-oss-how-to-run-and-fine-tune
  --temp 1.0 
  --top-p 1.0
  --top-k 0 
  --reasoning on
)
