# vim:set ts=8 sts=2 sw=2 tw=0 et ft=sh:

user="deepreinforce-ai"
model="Ornith-1.0-9B-GGUF"
quant="Q4_K_M"

args=(
  --temp 0.6 
  --top-p 0.95 
  --top-k 20 
  --min-p 0.00

  # Reasoning
  --reasoning on
  --reasoning-preserve

  # Prefill
  --flash-attn on
  -ctk q8_0 -ctv q8_0
)
